
name: First workflow

on:
  workflow_dispatch:  # for manually starting the workflow

jobs:
  first-job:
    runs-on: ubuntu-latest # runner to run job

    steps:
      - name: Print
        run: echo "CI/CD"

      - name: Print1
        run: echo "done"
